select  * from Employees;

select  * from DEPARTMENTS;
----SQL language is not case-sensitive
select  FIRST_NAME  from EMPLOYEES;
select  FIRST_NAME,LAST_NAME from EMPLOYEES;
select EMPLOYEE_ID from EMPLOYEES;
select  SALARY,EMAIL from EMPLOYEES;

--display all information from locations table
select  * from LOCATIONS;

--display country name andd region ID from countries
select  COUNTRY_NAME, REGION_ID from COUNTRIES;
-- display job id and job title from jobs table
select  JOB_ID , JOB_TITLE from JOBS;

